language: php
group: edge
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs